# Shinydashboard script for PIBE Database Management Dashboard

This script defines a Shiny dashboard with various tabs for managing and visualizing data related to the PIBE project. It utilizes Shinydashboard, leaflet, and plotly for interactive elements.

## Initialization

```{r, echo=FALSE}
# Logo
logo = '/www/img/anr-pibe-logo.gif'
# Include necessary libraries
suppressMessages(library(shiny))
suppressMessages(library(shinydashboard))
suppressMessages(library(shinyalert))
suppressMessages(library(shinyFiles))
suppressMessages(library(shinyWidgets))
suppressMessages(library(shinyTime))
suppressMessages(library(shinyjs))
suppressMessages(library(shinyBS))
suppressMessages(library(shinycssloaders))
suppressMessages(library(shinyobjects))
suppressMessages(library(sfheaders))
suppressMessages(library(concaveman))
suppressMessages(library(fontawesome))
suppressMessages(library(plotly))
suppressMessages(library(ggplot2))
suppressMessages(library(pkgdown))
```

## Dashboard
```{r header, echo=FALSE}
dashboardPage(
  ## Header Section
  dashboardHeader(
    ### Title
    title = 'PIBE Database Management Dashboard',
    tags$li(class = "dropdown",
            tags$a(href = 'https://www.anr-pibe.com/en', 
                   target = "_blank", 
                   tags$img(height = "20px", 
                            alt = "PIBE Logo", 
                            src = "https://www.anr-pibe.com/sites/pibe/files/anr-pibe-logo.gif", 
                            title= 'https://www.anr-pibe.com/en'))),
    ### Message menu
    dropdownMenuOutput('messageMenu'),
    
    ### Notifications
    dropdownMenu(type = 'tasks', headerText = "", 
                 notificationItem(text = textOutput("session_counter", inline = TRUE), icon = icon('clock')),
                 notificationItem(text = textOutput("server_start_datetime", inline = TRUE), icon = icon(name = 'clock')),
                 notificationItem(text = textOutput("pending_tasks", inline = TRUE), icon = icon(name = 'tasks')),
                 notificationItem(text = textOutput("max_task_wait_time", inline = TRUE), icon = icon(name = 'user-times')),
                 notificationItem(text = textOutput("active_shards_percent", inline = TRUE), icon = icon(name = 'user-times')),
                 notificationItem(text = textOutput("downloading_time", inline = TRUE), icon = icon(name = 'history'), status = 'warning')
                 ),
    ### Tasks
    dropdownMenu(type = 'tasks',
                 badgeStatus = 'success', headerText = "", 
                 uiOutput(outputId="active_shards")
                 ),
    ### Quit app
    tags$li(class = "dropdown",
            tags$button(id = 'closeApp', type = "button", class = "btn action-button", icon("stop-circle"), style = "color: #fff; background-color: red; border-color: #fff",
                onclick = "setTimeout(function(){window.close();},500);",  # close browser
                "Close window"),
            bsTooltip(id = "closeApp", title = "Quit app and close window", placement = "bottom", trigger = "hover", options = list(container = "header")),)
  ),  # End of dashboardHeader
  ## Sidebar Section
  dashboardSidebar(
    tags$style(HTML(".sidebar-menu li a { font-size: 20px; }")), 
    sidebarMenu(
      id = "sidebarid",
      ### PIBE project
      menuItem("PIBE project", tabName = "pibe_project", icon = icon("info")),
      ### Data download
      menuItem("Data download", tabName = "data_download", icon = icon("calendar")),
      ### Data visualization
      menuItem("Visualization", tabName = "visualization", icon = icon("image")),
      conditionalPanel('input.sidebarid == "visualization"',
                       fileInput('data_file', 'Choose file', accept=c('text/csv', 'text/comma-separated-values,text/plain')),
                       splitLayout(cellWidths = c("50%", "50%"),
                                   checkboxInput('jitter', 'Jitter'),
                                   checkboxInput('smooth', 'Smooth')),
                       selectInput('facet_row', label = 'Facet Row', choices = init$all_choices$facet_row),
                       uiOutput(outputId = 'facet_columns'),
                       uiOutput(outputId = 'color_plot')
                       ))), 
  ## Body Section
  dashboardBody(
    useShinyjs(),
    ### CSS file
    tags$link(rel = "stylesheet", type = "text/css", href = paste("html", "custom.css", sep = .Platform$file.sep)),
    tabItems(
      ### PIBE project presentation
      tabItem(tabName = "pibe_project",
              #' Show html files presenting the PIBE project and the WP2 package
              fluidRow(
                column(width = 12, uiOutput(outputId = "pibe_project_html"))), 
              fluidRow(
                column(width = 6, uiOutput(outputId = "pibe_project_WP2")), 
                column(width = 6, leafletOutput("map_tab_sensors"))),  # Map of sensors
              #' Table of sensors
              box(title = "Table of sensors", status = "primary", solidHeader = TRUE, collapsible = TRUE, width = 12, collapsed = TRUE,
                  dataTableOutput('table_sensors_tab_map')), 
              fluidRow(
                column(width = 12, uiOutput(outputId = "pibe_project_partners")))
      ),
      ### Data download
      tabItem(tabName = "data_download",
          box(title = "Dates and time sampling", width = 12, status = "primary", solidHeader = TRUE, collapsible = TRUE, 
              column(width = 8, 
                     splitLayout(cellWidths = c("30%", "70%"),
                                 dateInput("start_date_download", label = "from",
                                           value = init$selection$start_date, format = "yyyy/mm/dd"),
                                 timeInput("start_time_download", label = "at", 
                                           value = strptime(init$selection$start_time, "%H:%M"), seconds = FALSE)),
                     splitLayout(cellWidths = c("30%", "70%"),
                                 dateInput("end_date_download", label = "to", 
                                           value = init$selection$end_date, format = "yyyy/mm/dd"),
                                 timeInput("end_time_download", label = "at", 
                                           value = strptime(init$selection$end_time, "%H:%M"), seconds = FALSE))
              ),
              column(width = 4, 
                     radioButtons("time_sampling", label = "Time sampling", inline = FALSE, 
                                  selected = init$selection$time_sampling,  choices = init$all_choices$time_samplings))
          ),
          box(title = "Field(s), sensor(s) and indicator(s)", width = 6, status = "primary", solidHeader = TRUE, collapsible = TRUE, 
              prettyRadioButtons("scientific_domain", label = "Field(s)", 
                                 choiceNames = init$all_choices$scientific_domain.names, 
                                 choiceValues = init$all_choices$scientific_domain.values,  
                                 selected = "acoustic", inline = TRUE),
              splitLayout(cellWidths = c("33%", "33%", "33%"),
                          checkboxGroupInput("acoustic_sensors", label = "Acoustic sensor(s)", 
                                             choices = init$all_choices$acoustic_sensors, 
                                             selected = init$selection$acoustic_sensors),
                          checkboxGroupInput("acoustic_indicators", label = "Acoustic indicator(s)", 
                                             choices = init$all_choices$acoustic_indicators, 
                                             selected = init$selection$acoustic_indicators),
                          selectInput("acoustic_frequencies", "Frequencies", 
                                      choices = init$all_choices$acoustic_frequencies, 
                                      selected = init$selection$acoustic_frequencies, 
                                      multiple = TRUE, size = 5, selectize = FALSE)),
              splitLayout(cellWidths = c("33%", "33%", "33%"),
                          checkboxGroupInput("meteo_sensors", label = "Meteo sensor(s)", 
                                             choices = init$all_choices$meteo_sensors, 
                                             selected = init$selection$meteo_sensors),
                          checkboxGroupInput("meteo_variables", label = "Meteo variable(s)", 
                                             choices = init$all_choices$meteo_variables, 
                                             selected = init$selection$meteo_variables),
                          selectInput("acoustic_frequencies", "Frequencies", 
                                      choices = init$all_choices$acoustic_frequencies, 
                                      selected = init$selection$acoustic_frequencies, 
                                      multiple = TRUE, size = 5, selectize = FALSE))
          ),
          box(title = "Sensor map", status = "primary", solidHeader = TRUE, collapsible = TRUE, width = 6,
              leafletOutput("map_tab_visu"), 
              splitLayout(cellWidths = c("40%", "30%", "30%"), 
                          actionButton("reset_view_map_tab_visu", "Reset view"),
                          checkboxInput('selected_sensors', 'Highlight selected sensors', value = TRUE), 
                          checkboxInput('show_grid', 'Show/hide grid origin', value = TRUE))
              ),
          fluidRow(
            column(width = 2, align = "center", 
                   use_hover(),
                   hover_action_button(inputId = "connectionButton", label = "Connect", icon = icon(name = 'database'), class = "connect_button",
                                       button_animation = "pulse-grow", icon_animation = "spin"),
                   tags$head(tags$style(".connect_button{color: #fff} .connect_button{background-color: #c7c7c7;} .connect_button{border-color: #fff;} .connect_button{padding: 5px 14px 5px 14px;} .connect_button{margin: 5px 5px 5px 5px;}")),
                   uiOutput(outputId = "connect_button_style"),
                   uiOutput(outputId = "conn_bsTooltip")
                   ),
            column(width = 2, align = "center",
                   use_hover(),
                   hover_download_button(outputId = "downloadData", label = "Download", class = "download_data_button",
                                         button_animation = "pop", icon_animation = "spin"),
                   tags$head(tags$style(".download_data_button{color: #fff} .download_data_button{background-color: #27ae60;} .download_data_button{border-color: #fff;} .download_data_button{padding: 5px 14px 5px 14px;} .download_data_button{margin: 5px 5px 5px 5px;}")),
                   uiOutput(outputId = "download_data_button_style"),
                   uiOutput(outputId = "download_bsTooltip"),
                   ),
            column(width = 2, align = "left",
                   textOutput("download_button_disable_text")
            )
            # box(title = "Download selected dataset", width = 4, status = "primary", solidHeader = TRUE, collapsible = TRUE, 
            #     # column(width = 6, 
            #     #        shinyDirButton("downloadFolder", label = 'Select folder', 
            #     #                       title = 'Please select a destination folder', icon = icon("folder-open"))),
            #     column(width = 6, 
            #            downloadButton("downloadData", label = "Download")))
            # # box(title = "data paths:", 
            # #     h3("view"),
            # #     verbatimTextOutput("resultFolder"), br(),
            # #     h3("info"),
            # #     verbatimTextOutput("info"))
          )
      ),
      ### Visualization Section
      tabItem(tabName = "visualization",
        fluidRow(
          ## Time series visualization
          box(title = "Time series", width = 12, status = "primary", solidHeader = TRUE, collapsible = TRUE,
              plotlyOutput("acoustic_plot_tab_data", width = "100%") %>% withSpinner(color = "#0dc5c1"), 
              sliderInput("time_slider", label = "Viewing time slider", width = "100%",
                          min = as.POSIXct(x = init$selection$start_date_time, format = "%Y-%m-%d_%H:%M:%OS", tz = "UTC"),
                          max = as.POSIXct(x = init$selection$end_date_time, format = "%Y-%m-%d_%H:%M:%OS", tz = "UTC"),
                          value =  c(as.POSIXct(x = init$selection$start_date_time, format = "%Y-%m-%d_%H:%M:%OS", tz = "UTC"), 
                                     as.POSIXct(x = init$selection$end_date_time, format = "%Y-%m-%d_%H:%M:%OS", tz = "UTC")), 
                          timeFormat = "%d/%m %H:%M")),
          wellPanel(
            fluidRow(
              box(title = "Scatter plot", width = 12, status = "primary", solidHeader = TRUE, collapsible = TRUE, 
                  column(width = 2, 
                         selectInput(inputId = "scatter_plot_y_axis", label = "y-axis variable", multiple = FALSE, 
                                     selected = init$selection$observables[2], choices = init$selection$observables),
                         selectInput(inputId = "scatter_plot_x_axis", label = "x-axis variable", multiple = FALSE, 
                                     selected = init$selection$observables[1], choices = init$selection$observables),
                         selectInput(inputId = "scatter_plot_color", label = "color", multiple = FALSE, 
                                     selected = palette()[4], choices = palette())),
                  column(width = 10, 
                         plotlyOutput("scatter_plot"))
              ),
              box(title = "Table of acoustic data", status = "primary", solidHeader = TRUE, collapsible = TRUE, width = 12, collapsed = TRUE,
                  dataTableOutput('table_acoustic_tab_data'))
            )
          )
        )
      )
    ) # End of tabItems
  ), # End of dashboardBody
)
```